author: MiPal Griffith University
theme: fullwidth
#github_url: https://github.com/mipalgu/<Repo_Name>
#github_file_prefix: https://github.com/mipalgu/<Repo_Name>/tree/main
#root_url: <pages_url>
min_acl: private
